### ISSUE TITLE
Statistics missing for You

### ISSUE THREAD

**Issue by adunkman** [PaperCutSoftware/talk-o-meter#2]
:wave: Love the extension! 

I noticed recently that my own talk statistics are missing from calculations, and is missing from next to **You** (what the tile is called that references yourself). It makes the extension quite a bit less useful for 1:1s. :sob: 

The extension code looks pretty straightforward, so I may take a pass at spinning up a pull request.

- Any tips for what might be going on before digging into it? 
- Are you open for external contributions? 🤞 👯

**Comment by eugene-yao-zocdoc** [comment]
Came here to also report this.

**Comment by codedance** [comment]
Thanks for reporting.  I missed the first one from @adunkman as I was traveling (and did not see myself as I was finally doing face to face meetings!).  I'll jump on this today.

Note:  After I find an fix the issue, it will need to submitted to the Chrome Store and run through Google's review process.  Hence it may take a day or two to become available.  I'll keep everyone up to date here.

**Comment by codedance** [comment]
It turned out to be a hard problem to fine, but ultimately an easy fix - only 1 line of code changed!. I've pushed version 1.2 to the Google Chrome Extension Store.  Hopefully it will auto update in the next few days.

Thanks so much @adunkman and @eugene-yao-zocdoc for reporting the bug!

**Comment by codedance** [comment]
✅ Version 1.2 is now live:  https://chrome.google.com/webstore/detail/talk-o-meter-for-google-m/gkaddeikpkbebjdkaebhehephipjhocg

**Comment by adunkman** [comment]
Amazing! I have the update and it works great. Thank you, and I love the note highlighting the spot for next time! https://github.com/PaperCutSoftware/talk-o-meter/commit/bc3c97d674e28b8d46a7f8ebf737780c78e5ab7c
